from abc import ABC

# Robot Simulation Class
class SimulationState(ABC):
    def render(self, screen): ...
    def update(self, dt): ...
    def handle_event(self, event): ...
    def __init__(self): ...
    def exit_state(self): ...